# Generated by Django 2.2.5 on 2019-09-23 07:11

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.user_directory_path),
        ),
    ]
