# Generated by Django 2.2.5 on 2019-09-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='---', max_length=120, verbose_name='Nombre de URLS'),
            preserve_default=False,
        ),
    ]
