# Generated by Django 2.2.5 on 2019-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre de URLS'),
        ),
    ]
