# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180408_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
