# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20180325_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
