# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carritos', '0002_carrito_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('pagada', 'Pagada'), ('enviada', 'Enviada'), ('reembolsada', 'Reembolsada')], default='creada', max_length=20)),
                ('total_envio', models.DecimalField(decimal_places=2, default=99, max_digits=50)),
                ('total', models.DecimalField(decimal_places=2, default=99, max_digits=50)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.Carrito')),
            ],
        ),
    ]
