# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20180407_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='total_envio',
            new_name='costo_envio',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='total',
            new_name='sub_total',
        ),
    ]
